### ISSUE TITLE
Type hints and reflection

### ISSUE THREAD

**Issue by CRHough** [pyr/net#12]
Is there a measured need to avoid reflection? Several things break when type hints are applied (channel/channel, write! and write-and-flush! no longer working on groups, etc.)

**Comment by pyr** [comment]
I'll switch those to protocols to avoid breaking behavior.
Sorry to force you to run into these glitches, things are still in a bit of a flux.
As soon as things settle down, I will work on leveraging spec to write a range of tests which should make things more resilient.

Cheers!

**Comment by CRHough** [comment]
It's a beta. Don't worry about breaking things along the way to getting it right.

**Comment by mpenet** [comment]
My bad, I am likely the one to blame for some of the breakage, I did this a bit blindly (with the help of cider). We might be able to target interfaces/abstract classes to avoid some of the issues mentioned. I ll see if I can fix some of it today.

**Comment by pyr** [comment]
this is now fixed.
