### ISSUE TITLE
using the http.client library

### ISSUE THREAD

**Issue by hoebat** [pyr/net#51]
I'm trying to figure out how to use the http.client library. Is there a way to get a string output with a request?

```
(require 'net.http.client :as client)

(def bs (async/<!! (:body (client/request {:request-method :get :uri "http://www.bing.com"}))))
  
(slurp (binary/input-stream (.nioBuffer bs)))
=> ""
```

**Comment by pyr** [comment]
Hi @zcaudate,

Sorry for the late reply. I think Aleph should be used for now for a netty http client.

**Comment by hoebat** [comment]
@pyr: all good. I was looking for a basic http client.

Found this: https://github.com/schmee/java-http-clj
