### ISSUE TITLE
on Windows7

### ISSUE THREAD

**Issue by L-jasmine** [pyr/net#52]
#error {
 :cause Only supported on Linux
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.UnsatisfiedLinkError: failed to load the required native library, compiling:(core.clj:32:10)
   :at [clojure.lang.Compiler$InvokeExpr eval Compiler.java 3700]}
  {:type java.lang.UnsatisfiedLinkError
   :message failed to load the required native library
   :at [io.netty.channel.epoll.Epoll ensureAvailability Epoll.java 88]}
  {:type java.lang.ExceptionInInitializerError
   :message nil
   :at [io.netty.channel.epoll.Epoll <clinit> Epoll.java 39]}
  {:type java.lang.IllegalStateException
   :message Only supported on Linux
   :at [io.netty.channel.epoll.Native loadNativeLibrary Native.java 177]}]
 :trace
 [[io.netty.channel.epoll.Native loadNativeLibrary Native.java 177]
  [io.netty.channel.epoll.Native <clinit> Native.java 61]
  [io.netty.channel.epoll.Epoll <clinit> Epoll.java 39]
  [io.netty.channel.epoll.EpollEventLoop <clinit> EpollEventLoop.java 56]
  [io.netty.channel.epoll.EpollEventLoopGroup newChild EpollEventLoopGroup.java 134]
  [io.netty.channel.epoll.EpollEventLoopGroup newChild EpollEventLoopGroup.java 35]
  [io.netty.util.concurrent.MultithreadEventExecutorGroup <init> MultithreadEventExecutorGroup.java 84]
  [io.netty.util.concurrent.MultithreadEventExecutorGroup <init> MultithreadEventExecutorGroup.java 58]
  [io.netty.util.concurrent.MultithreadEventExecutorGroup <init> MultithreadEventExecutorGroup.java 47]
  [io.netty.channel.MultithreadEventLoopGroup <init> MultithreadEventLoopGroup.java 59]
  [io.netty.channel.epoll.EpollEventLoopGroup <init> EpollEventLoopGroup.java 104]
  [io.netty.channel.epoll.EpollEventLoopGroup <init> EpollEventLoopGroup.java 91]
  [io.netty.channel.epoll.EpollEventLoopGroup <init> EpollEventLoopGroup.java 68]
  [io.netty.channel.epoll.EpollEventLoopGroup <init> EpollEventLoopGroup.java 52]
  [io.netty.channel.epoll.EpollEventLoopGroup <init> EpollEventLoopGroup.java 45]
  [net.ty.bootstrap$epoll_event_loop_group invokeStatic bootstrap.clj 79]

**Comment by pyr** [comment]
Hi!

Net isn't supposed to be used with windows, sorry!
